server:
  port: 8000

spring:
  application:
    name: gateway-api
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.10.129:8848
    gateway:
      discovery:
        locator:
          enabled: true #使用服务发现路由   properties中的写法:   #spring.cloud.gateway.routes[1].id=service-edu
                                                                #spring.cloud.gateway.routes[1].uri=lb://service-edu
                                                                #spring.cloud.gateway.routes[1].predicates= Path=/eduservice/**
    # 配置service-edu服务
      routes:
        - id: service-edu
          uri: lb://service-edu
          predicates:
            - Path=/eduservice/** # 路径匹配