spring:
  application:
    name: service-edu
  profiles:
    active: dev
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xiaomao_edu?serverTimezone=GMT%2B8
    username: root
    password: 123456
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss #设置时间显示的格式
    time-zone: GMT+8 #设置时区
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.10.129:8848 #192.168.43.23:8848 #
  #redis配置
  redis:
    host: 192.168.10.129 #192.168.43.23
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5  #最大阻塞等待时间(负数表示没限制)
        min-idle: 0


server:
  port: 8001
mybatis-plus:
  #  configuration:
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 1 #逻辑删除值为1
      logic-not-delete-value: 0 #逻辑删除值为0
#logging:
#  level: info #设置日志级别

#开启熔断机制
feign:
  hystrix:
    enabled: true

# 设置hystrix超时时间，默认1000ms
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 6000