server:
  port: 8006

spring:
  application:
    name: service-order

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xiaomao_edu?serverTimezone=GMT%2B8
    username: root
    password: 123456

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss #设置时间显示的格式
    time-zone: GMT+8 #设置时区

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.10.129:8848 #192.168.43.23:8848 #
#mybati日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#开启熔断机制
feign:
  hystrix:
    enabled: true
# 设置hystrix超时时间，默认1000ms
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000

weixin:
  pay:
    #关联的公众号appid
    appid: wx74862e0dfcf69954
    #商户号
    partner: 1558950191
    #商户key
    partnerkey: T6m9iK73b0kn9g5v426MKfHQH7X8rKwb
    #回调地址
    notifyurl: http://guli.shop/api/order/weixinPay/weixinNotify